name: BrainrotEvents
version: '${project.version}'
main: Polfg.Polfg.BrainrotEvents
api-version: '1.20'
author: Polfg
commands:
  brainrotmusic:
    description: Manage Brainrot background music
    usage: /brainrotmusic <on|off|restart|reload|status>
permissions:
  brainrotevents.admin:
    description: Manage Brainrot background music
    default: op
