name: BrainrotEvents
version: '${project.version}'
main: Polfg.Polfg.BrainrotEvents
api-version: '1.20'
author: Polfg
softdepend: [BrainrotSpawner, WorldGuard, WorldEdit, FastAsyncWorldEdit]
commands:
  brainrotmusic:
    description: Manage Brainrot background music
    usage: /brainrotmusic <on|off|restart|reload|status>
  brainrotevent:
    description: Manage Brainrot world events
    usage: /brainrotevent <start <badweather|meteor|creeper|3road|2x|gum> [sec] | stop [event] | status | reload>
    aliases: [brevent, brainrotevents]
permissions:
  brainrotevents.admin:
    description: Manage Brainrot music and events
    default: op
